title: Arm AI Chat
email: han.yin@arm.com
description: >-
 On-Device LLM Chat, Right in Your Palm 
# TODO-han.yin: update the URL to be Google Play's app listing instead!
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "" # the subpath of your site, e.g. /blog
github_username:  hanyin-arm

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - index.markdown
  - privacy.markdown
exclude:
  - "*.md"
  - "**/*.md"
  - "**/*.template"
  - "**/*.html"
  